server:
  port: ${PORT:8888}
spring:
  application:
    name: CONFIG_SERVICE
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ProjectSoftwareArchitectureIUH/file_config_service.git
          clone-on-start: true
          default-label: main
#        bootstrap: false

eureka:
  instance:
    homePageUrl: https://${eureka.instance.hostName}/
    home-page-url-path: https://${eureka.instance.hostName}
  client:
    serviceUrl:
      defaultZone: http://servicediscorvery.herokuapp.com/eureka
      non-secure-port: 80
      secure-port: 443
