server:
  port: 8888
spring:
  application:
    name: CONFIG_SERVICE
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ProjectSoftwareArchitectureIUH/file_config_service.git
          default-label: main
#        bootstrap: false

eureka:
  client:
    register-with-eureka:
      value: true
    fetch-registry:
      value: true
    service-url:
      defaultZone: http://eureka.herokuapp.com/eureka
    instance:
      hostname: localhost